/* soapStub.h
   Generated by gSOAP 2.8.70 for postivoService.h

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#define SOAP_NAMESPACE_OF_ns1	"http://api.postivo.pl/webservices.php"

#ifndef soapStub_H
#define soapStub_H
#include "stdsoap2.h"
#if GSOAP_VERSION != 20870
# error "GSOAP VERSION 20870 MISMATCH IN GENERATED CODE VERSUS LIBRARY CODE: PLEASE REINSTALL PACKAGE"
#endif

#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************\
 *                                                                            *
 * Enumeration Types                                                          *
 *                                                                            *
\******************************************************************************/


/* postivoService.h:130 */
#ifndef SOAP_TYPE_xsd__boolean
#define SOAP_TYPE_xsd__boolean (7)
/* xsd:boolean */
enum xsd__boolean {
	xsd__boolean__false_ = 0,
	xsd__boolean__true_ = 1
};
#endif

/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Structs and Unions                                                         *
 *                                                                            *
\******************************************************************************/

struct ns1__DocumentFile;	/* postivoService.h:159 */
struct ns1__Recipient;	/* postivoService.h:176 */
struct ns1__Option;	/* postivoService.h:211 */
struct ns1__Shipment;	/* postivoService.h:228 */
struct ns1__ConfigProfile;	/* postivoService.h:275 */
struct ns1__Sender;	/* postivoService.h:306 */
struct ns1__ShipmentPrice;	/* postivoService.h:341 */
struct ns1__SenderData;	/* postivoService.h:378 */
struct ns1__DispatchReturnObject;	/* postivoService.h:409 */
struct ns1__BalanceReturnObject;	/* postivoService.h:430 */
struct ns1__ConfigProfilesReturnObject;	/* postivoService.h:455 */
struct ns1__SendersReturnObject;	/* postivoService.h:476 */
struct ns1__CertificateReturnObject;	/* postivoService.h:497 */
struct ns1__PriceReturnObject;	/* postivoService.h:520 */
struct ns1__AddSenderReturnObject;	/* postivoService.h:541 */
struct ns1__VerifySenderReturnObject;	/* postivoService.h:580 */
struct ns1__RemoveSenderReturnObject;	/* postivoService.h:599 */
struct ArrayOfDocumentFiles;	/* postivoService.h:619 */
struct ArrayOfRecipients;	/* postivoService.h:639 */
struct ArrayOfOptions;	/* postivoService.h:659 */
struct ArrayOfShipments;	/* postivoService.h:417 */
struct ArrayOfDispatchIds;	/* postivoService.h:699 */
struct ArrayOfConfigProfiles;	/* postivoService.h:463 */
struct ArrayOfSenders;	/* postivoService.h:484 */
struct ArrayOfShipmentsPrice;	/* postivoService.h:528 */
struct ns2__dispatchResponse;	/* postivoService.h:869 */
struct ns2__dispatch;	/* postivoService.h:937 */
struct ns2__getDispatchStatusResponse;	/* postivoService.h:948 */
struct ns2__getDispatchStatus;	/* postivoService.h:1007 */
struct ns2__getBalanceResponse;	/* postivoService.h:1018 */
struct ns2__getBalance;	/* postivoService.h:1074 */
struct ns2__getConfigProfilesResponse;	/* postivoService.h:1085 */
struct ns2__getConfigProfiles;	/* postivoService.h:1144 */
struct ns2__getSendersResponse;	/* postivoService.h:1155 */
struct ns2__getSenders;	/* postivoService.h:1211 */
struct ns2__getCertificateResponse;	/* postivoService.h:1222 */
struct ns2__getCertificate;	/* postivoService.h:1284 */
struct ns2__getPriceResponse;	/* postivoService.h:1295 */
struct ns2__getPrice;	/* postivoService.h:1363 */
struct ns2__addSenderResponse;	/* postivoService.h:1374 */
struct ns2__addSender;	/* postivoService.h:1436 */
struct ns2__verifySenderResponse;	/* postivoService.h:1447 */
struct ns2__verifySender;	/* postivoService.h:1509 */
struct ns2__removeSenderResponse;	/* postivoService.h:1520 */
struct ns2__removeSender;	/* postivoService.h:1579 */

/* postivoService.h:159 */
#ifndef SOAP_TYPE_ns1__DocumentFile
#define SOAP_TYPE_ns1__DocumentFile (8)
/* complex XSD type 'ns1:DocumentFile': */
struct ns1__DocumentFile {
        /** Required element 'file_stream' of XSD type 'xsd:string' */
        char *file_USCOREstream;
        /** Required element 'file_name' of XSD type 'xsd:string' */
        char *file_USCOREname;
};
#endif

/* postivoService.h:176 */
#ifndef SOAP_TYPE_ns1__Recipient
#define SOAP_TYPE_ns1__Recipient (9)
/* complex XSD type 'ns1:Recipient': */
struct ns1__Recipient {
        /** Required nillable (xsi:nil when NULL) element 'source' of XSD type 'xsd:string' */
        char *source;
        /** Required nillable (xsi:nil when NULL) element 'id' of XSD type 'xsd:int' */
        int *id;
        /** Required nillable (xsi:nil when NULL) element 'recipient_name' of XSD type 'xsd:string' */
        char *recipient_USCOREname;
        /** Required nillable (xsi:nil when NULL) element 'recipient_address_prefix' of XSD type 'xsd:string' */
        char *recipient_USCOREaddress_USCOREprefix;
        /** Required nillable (xsi:nil when NULL) element 'recipient_address' of XSD type 'xsd:string' */
        char *recipient_USCOREaddress;
        /** Required nillable (xsi:nil when NULL) element 'recipient_home_number' of XSD type 'xsd:string' */
        char *recipient_USCOREhome_USCOREnumber;
        /** Required nillable (xsi:nil when NULL) element 'recipient_flat_number' of XSD type 'xsd:string' */
        char *recipient_USCOREflat_USCOREnumber;
        /** Required nillable (xsi:nil when NULL) element 'recipient_post_code' of XSD type 'xsd:string' */
        char *recipient_USCOREpost_USCOREcode;
        /** Required nillable (xsi:nil when NULL) element 'recipient_city' of XSD type 'xsd:string' */
        char *recipient_USCOREcity;
        /** Required nillable (xsi:nil when NULL) element 'recipient_country' of XSD type 'xsd:string' */
        char *recipient_USCOREcountry;
        /** Required nillable (xsi:nil when NULL) element 'recipient_fax_number' of XSD type 'xsd:string' */
        char *recipient_USCOREfax_USCOREnumber;
};
#endif

/* postivoService.h:211 */
#ifndef SOAP_TYPE_ns1__Option
#define SOAP_TYPE_ns1__Option (11)
/* complex XSD type 'ns1:Option': */
struct ns1__Option {
        /** Required element 'name' of XSD type 'xsd:string' */
        char *name;
        /** Required element 'value' of XSD type 'xsd:string' */
        char *value;
};
#endif

/* postivoService.h:228 */
#ifndef SOAP_TYPE_ns1__Shipment
#define SOAP_TYPE_ns1__Shipment (12)
/* complex XSD type 'ns1:Shipment': */
struct ns1__Shipment {
        /** Optional element 'id' of XSD type 'xsd:string' */
        char *id;
        /** Optional element 'custom_id' of XSD type 'xsd:string' */
        char *custom_USCOREid;
        /** Optional element 'recipient_name' of XSD type 'xsd:string' */
        char *recipient_USCOREname;
        /** Optional element 'recipient_address' of XSD type 'xsd:string' */
        char *recipient_USCOREaddress;
        /** Optional element 'recipient_home_number' of XSD type 'xsd:string' */
        char *recipient_USCOREhome_USCOREnumber;
        /** Optional element 'recipient_flat_number' of XSD type 'xsd:string' */
        char *recipient_USCOREflat_USCOREnumber;
        /** Optional element 'recipient_post_code' of XSD type 'xsd:string' */
        char *recipient_USCOREpost_USCOREcode;
        /** Optional element 'recipient_city' of XSD type 'xsd:string' */
        char *recipient_USCOREcity;
        /** Optional element 'recipient_country' of XSD type 'xsd:string' */
        char *recipient_USCOREcountry;
        /** Optional element 'recipient_fax_number' of XSD type 'xsd:string' */
        char *recipient_USCOREfax_USCOREnumber;
        /** Optional element 'dispatch_carrier' of XSD type 'xsd:string' */
        char *dispatch_USCOREcarrier;
        /** Optional element 'dispatch_type' of XSD type 'xsd:string' */
        char *dispatch_USCOREtype;
        /** Optional element 'page_number' of XSD type 'xsd:int' */
        int *page_USCOREnumber;
        /** Optional element 'price' of XSD type 'xsd:float' */
        float *price;
        /** Optional element 'status' of XSD type 'xsd:string' */
        char *status;
        /** Optional element 'status_code' of XSD type 'xsd:string' */
        char *status_USCOREcode;
        /** Optional element 'status_description' of XSD type 'xsd:string' */
        char *status_USCOREdescription;
};
#endif

/* postivoService.h:275 */
#ifndef SOAP_TYPE_ns1__ConfigProfile
#define SOAP_TYPE_ns1__ConfigProfile (15)
/* complex XSD type 'ns1:ConfigProfile': */
struct ns1__ConfigProfile {
        /** Optional element 'config_id' of XSD type 'xsd:int' */
        int *config_USCOREid;
        /** Optional element 'config_name' of XSD type 'xsd:string' */
        char *config_USCOREname;
        /** Optional element 'paper_type' of XSD type 'xsd:string' */
        char *paper_USCOREtype;
        /** Optional element 'paper_print_type' of XSD type 'xsd:string' */
        char *paper_USCOREprint_USCOREtype;
        /** Optional element 'envelope_type' of XSD type 'xsd:string' */
        char *envelope_USCOREtype;
        /** Optional element 'envelope_template' of XSD type 'xsd:string' */
        char *envelope_USCOREtemplate;
        /** Optional element 'envelope_print_type' of XSD type 'xsd:string' */
        char *envelope_USCOREprint_USCOREtype;
        /** Optional element 'carrier' of XSD type 'xsd:string' */
        char *carrier;
        /** Optional element 'dispatch_type' of XSD type 'xsd:string' */
        char *dispatch_USCOREtype;
};
#endif

/* postivoService.h:306 */
#ifndef SOAP_TYPE_ns1__Sender
#define SOAP_TYPE_ns1__Sender (16)
/* complex XSD type 'ns1:Sender': */
struct ns1__Sender {
        /** Optional element 'sender_id' of XSD type 'xsd:int' */
        int *sender_USCOREid;
        /** Optional element 'sender_name' of XSD type 'xsd:string' */
        char *sender_USCOREname;
        /** Optional element 'sender_address' of XSD type 'xsd:string' */
        char *sender_USCOREaddress;
        /** Optional element 'sender_home_number' of XSD type 'xsd:string' */
        char *sender_USCOREhome_USCOREnumber;
        /** Optional element 'sender_flat_number' of XSD type 'xsd:string' */
        char *sender_USCOREflat_USCOREnumber;
        /** Optional element 'sender_post_code' of XSD type 'xsd:string' */
        char *sender_USCOREpost_USCOREcode;
        /** Optional element 'sender_city' of XSD type 'xsd:string' */
        char *sender_USCOREcity;
        /** Optional element 'sender_country' of XSD type 'xsd:string' */
        char *sender_USCOREcountry;
        /** Optional element 'sender_fax_number' of XSD type 'xsd:string' */
        char *sender_USCOREfax_USCOREnumber;
        /** Optional element 'default' of XSD type 'xsd:string' */
        char *default_;
        /** Optional element 'active' of XSD type 'xsd:string' */
        char *active;
};
#endif

/* postivoService.h:341 */
#ifndef SOAP_TYPE_ns1__ShipmentPrice
#define SOAP_TYPE_ns1__ShipmentPrice (17)
/* complex XSD type 'ns1:ShipmentPrice': */
struct ns1__ShipmentPrice {
        /** Optional element 'recipient_name' of XSD type 'xsd:string' */
        char *recipient_USCOREname;
        /** Optional element 'recipient_address' of XSD type 'xsd:string' */
        char *recipient_USCOREaddress;
        /** Optional element 'recipient_home_number' of XSD type 'xsd:string' */
        char *recipient_USCOREhome_USCOREnumber;
        /** Optional element 'recipient_flat_number' of XSD type 'xsd:string' */
        char *recipient_USCOREflat_USCOREnumber;
        /** Optional element 'recipient_post_code' of XSD type 'xsd:string' */
        char *recipient_USCOREpost_USCOREcode;
        /** Optional element 'recipient_city' of XSD type 'xsd:string' */
        char *recipient_USCOREcity;
        /** Optional element 'recipient_country' of XSD type 'xsd:string' */
        char *recipient_USCOREcountry;
        /** Optional element 'recipient_fax_number' of XSD type 'xsd:string' */
        char *recipient_USCOREfax_USCOREnumber;
        /** Optional element 'dispatch_carrier' of XSD type 'xsd:string' */
        char *dispatch_USCOREcarrier;
        /** Optional element 'dispatch_type' of XSD type 'xsd:string' */
        char *dispatch_USCOREtype;
        /** Optional element 'page_number' of XSD type 'xsd:int' */
        int *page_USCOREnumber;
        /** Optional element 'price' of XSD type 'xsd:float' */
        float *price;
};
#endif

/* postivoService.h:378 */
#ifndef SOAP_TYPE_ns1__SenderData
#define SOAP_TYPE_ns1__SenderData (18)
/* complex XSD type 'ns1:SenderData': */
struct ns1__SenderData {
        /** Optional element 'sender_name' of XSD type 'xsd:string' */
        char *sender_USCOREname;
        /** Optional element 'sender_address_prefix' of XSD type 'xsd:string' */
        char *sender_USCOREaddress_USCOREprefix;
        /** Optional element 'sender_address' of XSD type 'xsd:string' */
        char *sender_USCOREaddress;
        /** Optional element 'sender_home_number' of XSD type 'xsd:string' */
        char *sender_USCOREhome_USCOREnumber;
        /** Optional element 'sender_flat_number' of XSD type 'xsd:string' */
        char *sender_USCOREflat_USCOREnumber;
        /** Optional element 'sender_post_code' of XSD type 'xsd:string' */
        char *sender_USCOREpost_USCOREcode;
        /** Optional element 'sender_city' of XSD type 'xsd:string' */
        char *sender_USCOREcity;
        /** Optional element 'sender_country' of XSD type 'xsd:string' */
        char *sender_USCOREcountry;
        /** Optional element 'sender_fax_number' of XSD type 'xsd:string' */
        char *sender_USCOREfax_USCOREnumber;
};
#endif

/* postivoService.h:409 */
#ifndef SOAP_TYPE_ns1__DispatchReturnObject
#define SOAP_TYPE_ns1__DispatchReturnObject (19)
/* complex XSD type 'ns1:DispatchReturnObject': */
struct ns1__DispatchReturnObject {
        /** Required element 'result' of XSD type 'xsd:string' */
        char *result;
        /** Required element 'result_code' of XSD type 'xsd:string' */
        char *result_USCOREcode;
        /** Required element 'result_description' of XSD type 'xsd:string' */
        char *result_USCOREdescription;
        /** Required element 'shipments' of XSD type 'ArrayOfShipment' */
        struct ArrayOfShipments *shipments;
};
#endif

/* postivoService.h:430 */
#ifndef SOAP_TYPE_ns1__BalanceReturnObject
#define SOAP_TYPE_ns1__BalanceReturnObject (22)
/* complex XSD type 'ns1:BalanceReturnObject': */
struct ns1__BalanceReturnObject {
        /** Required element 'result' of XSD type 'xsd:string' */
        char *result;
        /** Required element 'result_code' of XSD type 'xsd:string' */
        char *result_USCOREcode;
        /** Required element 'result_description' of XSD type 'xsd:string' */
        char *result_USCOREdescription;
        /** Optional element 'balance' of XSD type 'xsd:float' */
        float *balance;
        /** Optional element 'limit' of XSD type 'xsd:float' */
        float *limit;
        /** Optional element 'postpaid' of XSD type 'xsd:int' */
        int *postpaid;
};
#endif

/* postivoService.h:455 */
#ifndef SOAP_TYPE_ns1__ConfigProfilesReturnObject
#define SOAP_TYPE_ns1__ConfigProfilesReturnObject (23)
/* complex XSD type 'ns1:ConfigProfilesReturnObject': */
struct ns1__ConfigProfilesReturnObject {
        /** Required element 'result' of XSD type 'xsd:string' */
        char *result;
        /** Required element 'result_code' of XSD type 'xsd:string' */
        char *result_USCOREcode;
        /** Required element 'result_description' of XSD type 'xsd:string' */
        char *result_USCOREdescription;
        /** Optional element 'config_profiles' of XSD type 'ArrayOfConfigProfile' */
        struct ArrayOfConfigProfiles *config_USCOREprofiles;
};
#endif

/* postivoService.h:476 */
#ifndef SOAP_TYPE_ns1__SendersReturnObject
#define SOAP_TYPE_ns1__SendersReturnObject (26)
/* complex XSD type 'ns1:SendersReturnObject': */
struct ns1__SendersReturnObject {
        /** Required element 'result' of XSD type 'xsd:string' */
        char *result;
        /** Required element 'result_code' of XSD type 'xsd:string' */
        char *result_USCOREcode;
        /** Required element 'result_description' of XSD type 'xsd:string' */
        char *result_USCOREdescription;
        /** Optional element 'senders' of XSD type 'ArrayOfSender' */
        struct ArrayOfSenders *senders;
};
#endif

/* postivoService.h:497 */
#ifndef SOAP_TYPE_ns1__CertificateReturnObject
#define SOAP_TYPE_ns1__CertificateReturnObject (29)
/* complex XSD type 'ns1:CertificateReturnObject': */
struct ns1__CertificateReturnObject {
        /** Required element 'result' of XSD type 'xsd:string' */
        char *result;
        /** Required element 'result_code' of XSD type 'xsd:string' */
        char *result_USCOREcode;
        /** Required element 'result_description' of XSD type 'xsd:string' */
        char *result_USCOREdescription;
        /** Required element 'cert_available' of XSD type 'xsd:boolean' */
        enum xsd__boolean cert_USCOREavailable;
        /** Optional element 'cert_content' of XSD type 'xsd:string' */
        char *cert_USCOREcontent;
};
#endif

/* postivoService.h:520 */
#ifndef SOAP_TYPE_ns1__PriceReturnObject
#define SOAP_TYPE_ns1__PriceReturnObject (30)
/* complex XSD type 'ns1:PriceReturnObject': */
struct ns1__PriceReturnObject {
        /** Required element 'result' of XSD type 'xsd:string' */
        char *result;
        /** Required element 'result_code' of XSD type 'xsd:string' */
        char *result_USCOREcode;
        /** Required element 'result_description' of XSD type 'xsd:string' */
        char *result_USCOREdescription;
        /** Required element 'shipments_price' of XSD type 'ArrayOfShipmentPrice' */
        struct ArrayOfShipmentsPrice *shipments_USCOREprice;
};
#endif

/* postivoService.h:541 */
#ifndef SOAP_TYPE_ns1__AddSenderReturnObject
#define SOAP_TYPE_ns1__AddSenderReturnObject (33)
/* complex XSD type 'ns1:AddSenderReturnObject': */
struct ns1__AddSenderReturnObject {
        /** Required element 'result' of XSD type 'xsd:string' */
        char *result;
        /** Required element 'result_code' of XSD type 'xsd:string' */
        char *result_USCOREcode;
        /** Required element 'result_description' of XSD type 'xsd:string' */
        char *result_USCOREdescription;
        /** Optional element 'sender_id' of XSD type 'xsd:int' */
        int *sender_USCOREid;
        /** Optional element 'shipment_id' of XSD type 'xsd:string' */
        char *shipment_USCOREid;
        /** Optional element 'sender_name' of XSD type 'xsd:string' */
        char *sender_USCOREname;
        /** Optional element 'sender_address' of XSD type 'xsd:string' */
        char *sender_USCOREaddress;
        /** Optional element 'sender_home_number' of XSD type 'xsd:string' */
        char *sender_USCOREhome_USCOREnumber;
        /** Optional element 'sender_flat_number' of XSD type 'xsd:string' */
        char *sender_USCOREflat_USCOREnumber;
        /** Optional element 'sender_post_code' of XSD type 'xsd:string' */
        char *sender_USCOREpost_USCOREcode;
        /** Optional element 'sender_city' of XSD type 'xsd:string' */
        char *sender_USCOREcity;
        /** Optional element 'sender_country' of XSD type 'xsd:string' */
        char *sender_USCOREcountry;
        /** Optional element 'sender_fax_number' of XSD type 'xsd:string' */
        char *sender_USCOREfax_USCOREnumber;
};
#endif

/* postivoService.h:580 */
#ifndef SOAP_TYPE_ns1__VerifySenderReturnObject
#define SOAP_TYPE_ns1__VerifySenderReturnObject (34)
/* complex XSD type 'ns1:VerifySenderReturnObject': */
struct ns1__VerifySenderReturnObject {
        /** Required element 'result' of XSD type 'xsd:string' */
        char *result;
        /** Required element 'result_code' of XSD type 'xsd:string' */
        char *result_USCOREcode;
        /** Required element 'result_description' of XSD type 'xsd:string' */
        char *result_USCOREdescription;
};
#endif

/* postivoService.h:599 */
#ifndef SOAP_TYPE_ns1__RemoveSenderReturnObject
#define SOAP_TYPE_ns1__RemoveSenderReturnObject (35)
/* complex XSD type 'ns1:RemoveSenderReturnObject': */
struct ns1__RemoveSenderReturnObject {
        /** Required element 'result' of XSD type 'xsd:string' */
        char *result;
        /** Required element 'result_code' of XSD type 'xsd:string' */
        char *result_USCOREcode;
        /** Required element 'result_description' of XSD type 'xsd:string' */
        char *result_USCOREdescription;
};
#endif

/* postivoService.h:619 */
#ifndef SOAP_TYPE_ArrayOfDocumentFiles
#define SOAP_TYPE_ArrayOfDocumentFiles (36)
/* SOAP encoded array of ns1:DocumentFile schema type: */
struct ArrayOfDocumentFiles {
        struct ns1__DocumentFile **__ptr;
        int __size;
};
#endif

/* postivoService.h:639 */
#ifndef SOAP_TYPE_ArrayOfRecipients
#define SOAP_TYPE_ArrayOfRecipients (39)
/* SOAP encoded array of ns1:Recipient schema type: */
struct ArrayOfRecipients {
        struct ns1__Recipient **__ptr;
        int __size;
};
#endif

/* postivoService.h:659 */
#ifndef SOAP_TYPE_ArrayOfOptions
#define SOAP_TYPE_ArrayOfOptions (42)
/* SOAP encoded array of ns1:Option schema type: */
struct ArrayOfOptions {
        struct ns1__Option **__ptr;
        int __size;
};
#endif

/* postivoService.h:417 */
#ifndef SOAP_TYPE_ArrayOfShipments
#define SOAP_TYPE_ArrayOfShipments (20)
/* SOAP encoded array of ns1:Shipment schema type: */
struct ArrayOfShipments {
        struct ns1__Shipment **__ptr;
        int __size;
};
#endif

/* postivoService.h:699 */
#ifndef SOAP_TYPE_ArrayOfDispatchIds
#define SOAP_TYPE_ArrayOfDispatchIds (47)
/* SOAP encoded array of xsd:string schema type: */
struct ArrayOfDispatchIds {
        char **__ptr;
        int __size;
};
#endif

/* postivoService.h:463 */
#ifndef SOAP_TYPE_ArrayOfConfigProfiles
#define SOAP_TYPE_ArrayOfConfigProfiles (24)
/* SOAP encoded array of ns1:ConfigProfile schema type: */
struct ArrayOfConfigProfiles {
        struct ns1__ConfigProfile **__ptr;
        int __size;
};
#endif

/* postivoService.h:484 */
#ifndef SOAP_TYPE_ArrayOfSenders
#define SOAP_TYPE_ArrayOfSenders (27)
/* SOAP encoded array of ns1:Sender schema type: */
struct ArrayOfSenders {
        struct ns1__Sender **__ptr;
        int __size;
};
#endif

/* postivoService.h:528 */
#ifndef SOAP_TYPE_ArrayOfShipmentsPrice
#define SOAP_TYPE_ArrayOfShipmentsPrice (31)
/* SOAP encoded array of ns1:ShipmentPrice schema type: */
struct ArrayOfShipmentsPrice {
        struct ns1__ShipmentPrice **__ptr;
        int __size;
};
#endif

/* postivoService.h:869 */
#ifndef SOAP_TYPE_ns2__dispatchResponse
#define SOAP_TYPE_ns2__dispatchResponse (55)
/* complex XSD type 'ns2:dispatchResponse': */
struct ns2__dispatchResponse {
        /** Optional element 'return' of XSD type 'ns1:DispatchReturnObject' */
        struct ns1__DispatchReturnObject *return_;
};
#endif

/* postivoService.h:937 */
#ifndef SOAP_TYPE_ns2__dispatch
#define SOAP_TYPE_ns2__dispatch (62)
/* complex XSD type 'ns2:dispatch': */
struct ns2__dispatch {
        /** Optional element 'login' of XSD type 'xsd:string' */
        char *login;
        /** Optional element 'api_pass' of XSD type 'xsd:string' */
        char *api_USCOREpass;
        /** Optional element 'msg_type' of XSD type 'xsd:string' */
        char *msg_USCOREtype;
        /** Optional element 'document_files' of XSD type 'ArrayOfDocumentFile' */
        struct ArrayOfDocumentFiles *document_USCOREfiles;
        /** Optional element 'recipients' of XSD type 'ArrayOfRecipient' */
        struct ArrayOfRecipients *recipients;
        /** Optional element 'options' of XSD type 'ArrayOfOption' */
        struct ArrayOfOptions *options;
};
#endif

/* postivoService.h:948 */
#ifndef SOAP_TYPE_ns2__getDispatchStatusResponse
#define SOAP_TYPE_ns2__getDispatchStatusResponse (63)
/* complex XSD type 'ns2:getDispatchStatusResponse': */
struct ns2__getDispatchStatusResponse {
        /** Optional element 'return' of XSD type 'ns1:DispatchReturnObject' */
        struct ns1__DispatchReturnObject *return_;
};
#endif

/* postivoService.h:1007 */
#ifndef SOAP_TYPE_ns2__getDispatchStatus
#define SOAP_TYPE_ns2__getDispatchStatus (67)
/* complex XSD type 'ns2:getDispatchStatus': */
struct ns2__getDispatchStatus {
        /** Optional element 'login' of XSD type 'xsd:string' */
        char *login;
        /** Optional element 'api_pass' of XSD type 'xsd:string' */
        char *api_USCOREpass;
        /** Optional element 'dispatch_ids' of XSD type 'ArrayOfstring' */
        struct ArrayOfDispatchIds *dispatch_USCOREids;
};
#endif

/* postivoService.h:1018 */
#ifndef SOAP_TYPE_ns2__getBalanceResponse
#define SOAP_TYPE_ns2__getBalanceResponse (68)
/* complex XSD type 'ns2:getBalanceResponse': */
struct ns2__getBalanceResponse {
        /** Optional element 'return' of XSD type 'ns1:BalanceReturnObject' */
        struct ns1__BalanceReturnObject *return_;
};
#endif

/* postivoService.h:1074 */
#ifndef SOAP_TYPE_ns2__getBalance
#define SOAP_TYPE_ns2__getBalance (72)
/* complex XSD type 'ns2:getBalance': */
struct ns2__getBalance {
        /** Optional element 'login' of XSD type 'xsd:string' */
        char *login;
        /** Optional element 'api_pass' of XSD type 'xsd:string' */
        char *api_USCOREpass;
};
#endif

/* postivoService.h:1085 */
#ifndef SOAP_TYPE_ns2__getConfigProfilesResponse
#define SOAP_TYPE_ns2__getConfigProfilesResponse (73)
/* complex XSD type 'ns2:getConfigProfilesResponse': */
struct ns2__getConfigProfilesResponse {
        /** Optional element 'return' of XSD type 'ns1:ConfigProfilesReturnObject' */
        struct ns1__ConfigProfilesReturnObject *return_;
};
#endif

/* postivoService.h:1144 */
#ifndef SOAP_TYPE_ns2__getConfigProfiles
#define SOAP_TYPE_ns2__getConfigProfiles (77)
/* complex XSD type 'ns2:getConfigProfiles': */
struct ns2__getConfigProfiles {
        /** Optional element 'login' of XSD type 'xsd:string' */
        char *login;
        /** Optional element 'api_pass' of XSD type 'xsd:string' */
        char *api_USCOREpass;
        /** Optional element 'msg_type' of XSD type 'xsd:string' */
        char *msg_USCOREtype;
};
#endif

/* postivoService.h:1155 */
#ifndef SOAP_TYPE_ns2__getSendersResponse
#define SOAP_TYPE_ns2__getSendersResponse (78)
/* complex XSD type 'ns2:getSendersResponse': */
struct ns2__getSendersResponse {
        /** Optional element 'return' of XSD type 'ns1:SendersReturnObject' */
        struct ns1__SendersReturnObject *return_;
};
#endif

/* postivoService.h:1211 */
#ifndef SOAP_TYPE_ns2__getSenders
#define SOAP_TYPE_ns2__getSenders (82)
/* complex XSD type 'ns2:getSenders': */
struct ns2__getSenders {
        /** Optional element 'login' of XSD type 'xsd:string' */
        char *login;
        /** Optional element 'api_pass' of XSD type 'xsd:string' */
        char *api_USCOREpass;
};
#endif

/* postivoService.h:1222 */
#ifndef SOAP_TYPE_ns2__getCertificateResponse
#define SOAP_TYPE_ns2__getCertificateResponse (83)
/* complex XSD type 'ns2:getCertificateResponse': */
struct ns2__getCertificateResponse {
        /** Optional element 'return' of XSD type 'ns1:CertificateReturnObject' */
        struct ns1__CertificateReturnObject *return_;
};
#endif

/* postivoService.h:1284 */
#ifndef SOAP_TYPE_ns2__getCertificate
#define SOAP_TYPE_ns2__getCertificate (87)
/* complex XSD type 'ns2:getCertificate': */
struct ns2__getCertificate {
        /** Optional element 'login' of XSD type 'xsd:string' */
        char *login;
        /** Optional element 'api_pass' of XSD type 'xsd:string' */
        char *api_USCOREpass;
        /** Optional element 'dispatch_id' of XSD type 'xsd:string' */
        char *dispatch_USCOREid;
        /** Required element 'certificate_type' of XSD type 'xsd:int' */
        int certificate_USCOREtype;
};
#endif

/* postivoService.h:1295 */
#ifndef SOAP_TYPE_ns2__getPriceResponse
#define SOAP_TYPE_ns2__getPriceResponse (88)
/* complex XSD type 'ns2:getPriceResponse': */
struct ns2__getPriceResponse {
        /** Optional element 'return' of XSD type 'ns1:PriceReturnObject' */
        struct ns1__PriceReturnObject *return_;
};
#endif

/* postivoService.h:1363 */
#ifndef SOAP_TYPE_ns2__getPrice
#define SOAP_TYPE_ns2__getPrice (92)
/* complex XSD type 'ns2:getPrice': */
struct ns2__getPrice {
        /** Optional element 'login' of XSD type 'xsd:string' */
        char *login;
        /** Optional element 'api_pass' of XSD type 'xsd:string' */
        char *api_USCOREpass;
        /** Optional element 'msg_type' of XSD type 'xsd:string' */
        char *msg_USCOREtype;
        /** Optional element 'document_files' of XSD type 'ArrayOfDocumentFile' */
        struct ArrayOfDocumentFiles *document_USCOREfiles;
        /** Optional element 'recipients' of XSD type 'ArrayOfRecipient' */
        struct ArrayOfRecipients *recipients;
        /** Required element 'config_id' of XSD type 'xsd:int' */
        int config_USCOREid;
};
#endif

/* postivoService.h:1374 */
#ifndef SOAP_TYPE_ns2__addSenderResponse
#define SOAP_TYPE_ns2__addSenderResponse (93)
/* complex XSD type 'ns2:addSenderResponse': */
struct ns2__addSenderResponse {
        /** Optional element 'return' of XSD type 'ns1:AddSenderReturnObject' */
        struct ns1__AddSenderReturnObject *return_;
};
#endif

/* postivoService.h:1436 */
#ifndef SOAP_TYPE_ns2__addSender
#define SOAP_TYPE_ns2__addSender (98)
/* complex XSD type 'ns2:addSender': */
struct ns2__addSender {
        /** Optional element 'login' of XSD type 'xsd:string' */
        char *login;
        /** Optional element 'api_pass' of XSD type 'xsd:string' */
        char *api_USCOREpass;
        /** Optional element 'sender_data' of XSD type 'ns1:SenderData' */
        struct ns1__SenderData *sender_USCOREdata;
        /** Required element 'accept_terms' of XSD type 'xsd:boolean' */
        enum xsd__boolean accept_USCOREterms;
};
#endif

/* postivoService.h:1447 */
#ifndef SOAP_TYPE_ns2__verifySenderResponse
#define SOAP_TYPE_ns2__verifySenderResponse (99)
/* complex XSD type 'ns2:verifySenderResponse': */
struct ns2__verifySenderResponse {
        /** Optional element 'return' of XSD type 'ns1:VerifySenderReturnObject' */
        struct ns1__VerifySenderReturnObject *return_;
};
#endif

/* postivoService.h:1509 */
#ifndef SOAP_TYPE_ns2__verifySender
#define SOAP_TYPE_ns2__verifySender (103)
/* complex XSD type 'ns2:verifySender': */
struct ns2__verifySender {
        /** Optional element 'login' of XSD type 'xsd:string' */
        char *login;
        /** Optional element 'api_pass' of XSD type 'xsd:string' */
        char *api_USCOREpass;
        /** Required element 'sender_id' of XSD type 'xsd:int' */
        int sender_USCOREid;
        /** Optional element 'verification_code' of XSD type 'xsd:string' */
        char *verification_USCOREcode;
};
#endif

/* postivoService.h:1520 */
#ifndef SOAP_TYPE_ns2__removeSenderResponse
#define SOAP_TYPE_ns2__removeSenderResponse (104)
/* complex XSD type 'ns2:removeSenderResponse': */
struct ns2__removeSenderResponse {
        /** Optional element 'return' of XSD type 'ns1:RemoveSenderReturnObject' */
        struct ns1__RemoveSenderReturnObject *return_;
};
#endif

/* postivoService.h:1579 */
#ifndef SOAP_TYPE_ns2__removeSender
#define SOAP_TYPE_ns2__removeSender (108)
/* complex XSD type 'ns2:removeSender': */
struct ns2__removeSender {
        /** Optional element 'login' of XSD type 'xsd:string' */
        char *login;
        /** Optional element 'api_pass' of XSD type 'xsd:string' */
        char *api_USCOREpass;
        /** Required element 'sender_id' of XSD type 'xsd:int' */
        int sender_USCOREid;
};
#endif

/* postivoService.h:1640 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (109)
/* SOAP_ENV__Header: */
struct SOAP_ENV__Header {
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* empty struct is a GNU extension */
#endif
};
#endif
#endif

/* postivoService.h:1640 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (110)
/* Type SOAP_ENV__Code is a recursive data type, (in)directly referencing itself through its (base or derived class) members */
/* SOAP_ENV__Code: */
struct SOAP_ENV__Code {
        /** Optional element 'SOAP-ENV:Value' of XSD type 'xsd:QName' */
        char *SOAP_ENV__Value;
        /** Optional element 'SOAP-ENV:Subcode' of XSD type 'SOAP-ENV:Code' */
        struct SOAP_ENV__Code *SOAP_ENV__Subcode;
};
#endif
#endif

/* postivoService.h:1640 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (112)
/* SOAP_ENV__Detail: */
struct SOAP_ENV__Detail {
        char *__any;
        /** Any type of element 'fault' assigned to fault with its SOAP_TYPE_T assigned to __type */
        /** Do not create a cyclic data structure throught this member unless SOAP encoding or SOAP_XML_GRAPH are used for id-ref serialization */
        int __type;
        void *fault;
};
#endif
#endif

/* postivoService.h:1640 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (115)
/* SOAP_ENV__Reason: */
struct SOAP_ENV__Reason {
        /** Optional element 'SOAP-ENV:Text' of XSD type 'xsd:string' */
        char *SOAP_ENV__Text;
};
#endif
#endif

/* postivoService.h:1640 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (116)
/* SOAP_ENV__Fault: */
struct SOAP_ENV__Fault {
        /** Optional element 'faultcode' of XSD type 'xsd:QName' */
        char *faultcode;
        /** Optional element 'faultstring' of XSD type 'xsd:string' */
        char *faultstring;
        /** Optional element 'faultactor' of XSD type 'xsd:string' */
        char *faultactor;
        /** Optional element 'detail' of XSD type 'SOAP-ENV:Detail' */
        struct SOAP_ENV__Detail *detail;
        /** Optional element 'SOAP-ENV:Code' of XSD type 'SOAP-ENV:Code' */
        struct SOAP_ENV__Code *SOAP_ENV__Code;
        /** Optional element 'SOAP-ENV:Reason' of XSD type 'SOAP-ENV:Reason' */
        struct SOAP_ENV__Reason *SOAP_ENV__Reason;
        /** Optional element 'SOAP-ENV:Node' of XSD type 'xsd:string' */
        char *SOAP_ENV__Node;
        /** Optional element 'SOAP-ENV:Role' of XSD type 'xsd:string' */
        char *SOAP_ENV__Role;
        /** Optional element 'SOAP-ENV:Detail' of XSD type 'SOAP-ENV:Detail' */
        struct SOAP_ENV__Detail *SOAP_ENV__Detail;
};
#endif
#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/


/* (built-in):0 */
#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (5)
typedef char *_XML;
#endif

/* (built-in):0 */
#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (6)
typedef char *_QName;
#endif

/******************************************************************************\
 *                                                                            *
 * Serializable Types                                                         *
 *                                                                            *
\******************************************************************************/


/* char has binding name 'byte' for type 'xsd:byte' */
#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif

/* int has binding name 'int' for type 'xsd:int' */
#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif

/* float has binding name 'float' for type 'xsd:float' */
#ifndef SOAP_TYPE_float
#define SOAP_TYPE_float (13)
#endif

/* enum xsd__boolean has binding name 'xsd__boolean' for type 'xsd:boolean' */
#ifndef SOAP_TYPE_xsd__boolean
#define SOAP_TYPE_xsd__boolean (7)
#endif

/* struct SOAP_ENV__Fault has binding name 'SOAP_ENV__Fault' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (116)
#endif

/* struct SOAP_ENV__Reason has binding name 'SOAP_ENV__Reason' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (115)
#endif

/* struct SOAP_ENV__Detail has binding name 'SOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (112)
#endif

/* struct SOAP_ENV__Code has binding name 'SOAP_ENV__Code' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (110)
#endif

/* struct SOAP_ENV__Header has binding name 'SOAP_ENV__Header' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (109)
#endif

/* struct ns2__removeSender has binding name 'ns2__removeSender' for type 'ns2:removeSender' */
#ifndef SOAP_TYPE_ns2__removeSender
#define SOAP_TYPE_ns2__removeSender (108)
#endif

/* struct ns2__removeSenderResponse has binding name 'ns2__removeSenderResponse' for type 'ns2:removeSenderResponse' */
#ifndef SOAP_TYPE_ns2__removeSenderResponse
#define SOAP_TYPE_ns2__removeSenderResponse (104)
#endif

/* struct ns2__verifySender has binding name 'ns2__verifySender' for type 'ns2:verifySender' */
#ifndef SOAP_TYPE_ns2__verifySender
#define SOAP_TYPE_ns2__verifySender (103)
#endif

/* struct ns2__verifySenderResponse has binding name 'ns2__verifySenderResponse' for type 'ns2:verifySenderResponse' */
#ifndef SOAP_TYPE_ns2__verifySenderResponse
#define SOAP_TYPE_ns2__verifySenderResponse (99)
#endif

/* struct ns2__addSender has binding name 'ns2__addSender' for type 'ns2:addSender' */
#ifndef SOAP_TYPE_ns2__addSender
#define SOAP_TYPE_ns2__addSender (98)
#endif

/* struct ns2__addSenderResponse has binding name 'ns2__addSenderResponse' for type 'ns2:addSenderResponse' */
#ifndef SOAP_TYPE_ns2__addSenderResponse
#define SOAP_TYPE_ns2__addSenderResponse (93)
#endif

/* struct ns2__getPrice has binding name 'ns2__getPrice' for type 'ns2:getPrice' */
#ifndef SOAP_TYPE_ns2__getPrice
#define SOAP_TYPE_ns2__getPrice (92)
#endif

/* struct ns2__getPriceResponse has binding name 'ns2__getPriceResponse' for type 'ns2:getPriceResponse' */
#ifndef SOAP_TYPE_ns2__getPriceResponse
#define SOAP_TYPE_ns2__getPriceResponse (88)
#endif

/* struct ns2__getCertificate has binding name 'ns2__getCertificate' for type 'ns2:getCertificate' */
#ifndef SOAP_TYPE_ns2__getCertificate
#define SOAP_TYPE_ns2__getCertificate (87)
#endif

/* struct ns2__getCertificateResponse has binding name 'ns2__getCertificateResponse' for type 'ns2:getCertificateResponse' */
#ifndef SOAP_TYPE_ns2__getCertificateResponse
#define SOAP_TYPE_ns2__getCertificateResponse (83)
#endif

/* struct ns2__getSenders has binding name 'ns2__getSenders' for type 'ns2:getSenders' */
#ifndef SOAP_TYPE_ns2__getSenders
#define SOAP_TYPE_ns2__getSenders (82)
#endif

/* struct ns2__getSendersResponse has binding name 'ns2__getSendersResponse' for type 'ns2:getSendersResponse' */
#ifndef SOAP_TYPE_ns2__getSendersResponse
#define SOAP_TYPE_ns2__getSendersResponse (78)
#endif

/* struct ns2__getConfigProfiles has binding name 'ns2__getConfigProfiles' for type 'ns2:getConfigProfiles' */
#ifndef SOAP_TYPE_ns2__getConfigProfiles
#define SOAP_TYPE_ns2__getConfigProfiles (77)
#endif

/* struct ns2__getConfigProfilesResponse has binding name 'ns2__getConfigProfilesResponse' for type 'ns2:getConfigProfilesResponse' */
#ifndef SOAP_TYPE_ns2__getConfigProfilesResponse
#define SOAP_TYPE_ns2__getConfigProfilesResponse (73)
#endif

/* struct ns2__getBalance has binding name 'ns2__getBalance' for type 'ns2:getBalance' */
#ifndef SOAP_TYPE_ns2__getBalance
#define SOAP_TYPE_ns2__getBalance (72)
#endif

/* struct ns2__getBalanceResponse has binding name 'ns2__getBalanceResponse' for type 'ns2:getBalanceResponse' */
#ifndef SOAP_TYPE_ns2__getBalanceResponse
#define SOAP_TYPE_ns2__getBalanceResponse (68)
#endif

/* struct ns2__getDispatchStatus has binding name 'ns2__getDispatchStatus' for type 'ns2:getDispatchStatus' */
#ifndef SOAP_TYPE_ns2__getDispatchStatus
#define SOAP_TYPE_ns2__getDispatchStatus (67)
#endif

/* struct ns2__getDispatchStatusResponse has binding name 'ns2__getDispatchStatusResponse' for type 'ns2:getDispatchStatusResponse' */
#ifndef SOAP_TYPE_ns2__getDispatchStatusResponse
#define SOAP_TYPE_ns2__getDispatchStatusResponse (63)
#endif

/* struct ns2__dispatch has binding name 'ns2__dispatch' for type 'ns2:dispatch' */
#ifndef SOAP_TYPE_ns2__dispatch
#define SOAP_TYPE_ns2__dispatch (62)
#endif

/* struct ns2__dispatchResponse has binding name 'ns2__dispatchResponse' for type 'ns2:dispatchResponse' */
#ifndef SOAP_TYPE_ns2__dispatchResponse
#define SOAP_TYPE_ns2__dispatchResponse (55)
#endif

/* struct ArrayOfDispatchIds has binding name 'ArrayOfDispatchIds' for type 'xsd:string' */
#ifndef SOAP_TYPE_ArrayOfDispatchIds
#define SOAP_TYPE_ArrayOfDispatchIds (47)
#endif

/* struct ArrayOfOptions has binding name 'ArrayOfOptions' for type 'ns1:Option' */
#ifndef SOAP_TYPE_ArrayOfOptions
#define SOAP_TYPE_ArrayOfOptions (42)
#endif

/* struct ArrayOfRecipients has binding name 'ArrayOfRecipients' for type 'ns1:Recipient' */
#ifndef SOAP_TYPE_ArrayOfRecipients
#define SOAP_TYPE_ArrayOfRecipients (39)
#endif

/* struct ArrayOfDocumentFiles has binding name 'ArrayOfDocumentFiles' for type 'ns1:DocumentFile' */
#ifndef SOAP_TYPE_ArrayOfDocumentFiles
#define SOAP_TYPE_ArrayOfDocumentFiles (36)
#endif

/* struct ns1__RemoveSenderReturnObject has binding name 'ns1__RemoveSenderReturnObject' for type 'ns1:RemoveSenderReturnObject' */
#ifndef SOAP_TYPE_ns1__RemoveSenderReturnObject
#define SOAP_TYPE_ns1__RemoveSenderReturnObject (35)
#endif

/* struct ns1__VerifySenderReturnObject has binding name 'ns1__VerifySenderReturnObject' for type 'ns1:VerifySenderReturnObject' */
#ifndef SOAP_TYPE_ns1__VerifySenderReturnObject
#define SOAP_TYPE_ns1__VerifySenderReturnObject (34)
#endif

/* struct ns1__AddSenderReturnObject has binding name 'ns1__AddSenderReturnObject' for type 'ns1:AddSenderReturnObject' */
#ifndef SOAP_TYPE_ns1__AddSenderReturnObject
#define SOAP_TYPE_ns1__AddSenderReturnObject (33)
#endif

/* struct ArrayOfShipmentsPrice has binding name 'ArrayOfShipmentsPrice' for type 'ns1:ShipmentPrice' */
#ifndef SOAP_TYPE_ArrayOfShipmentsPrice
#define SOAP_TYPE_ArrayOfShipmentsPrice (31)
#endif

/* struct ns1__PriceReturnObject has binding name 'ns1__PriceReturnObject' for type 'ns1:PriceReturnObject' */
#ifndef SOAP_TYPE_ns1__PriceReturnObject
#define SOAP_TYPE_ns1__PriceReturnObject (30)
#endif

/* struct ns1__CertificateReturnObject has binding name 'ns1__CertificateReturnObject' for type 'ns1:CertificateReturnObject' */
#ifndef SOAP_TYPE_ns1__CertificateReturnObject
#define SOAP_TYPE_ns1__CertificateReturnObject (29)
#endif

/* struct ArrayOfSenders has binding name 'ArrayOfSenders' for type 'ns1:Sender' */
#ifndef SOAP_TYPE_ArrayOfSenders
#define SOAP_TYPE_ArrayOfSenders (27)
#endif

/* struct ns1__SendersReturnObject has binding name 'ns1__SendersReturnObject' for type 'ns1:SendersReturnObject' */
#ifndef SOAP_TYPE_ns1__SendersReturnObject
#define SOAP_TYPE_ns1__SendersReturnObject (26)
#endif

/* struct ArrayOfConfigProfiles has binding name 'ArrayOfConfigProfiles' for type 'ns1:ConfigProfile' */
#ifndef SOAP_TYPE_ArrayOfConfigProfiles
#define SOAP_TYPE_ArrayOfConfigProfiles (24)
#endif

/* struct ns1__ConfigProfilesReturnObject has binding name 'ns1__ConfigProfilesReturnObject' for type 'ns1:ConfigProfilesReturnObject' */
#ifndef SOAP_TYPE_ns1__ConfigProfilesReturnObject
#define SOAP_TYPE_ns1__ConfigProfilesReturnObject (23)
#endif

/* struct ns1__BalanceReturnObject has binding name 'ns1__BalanceReturnObject' for type 'ns1:BalanceReturnObject' */
#ifndef SOAP_TYPE_ns1__BalanceReturnObject
#define SOAP_TYPE_ns1__BalanceReturnObject (22)
#endif

/* struct ArrayOfShipments has binding name 'ArrayOfShipments' for type 'ns1:Shipment' */
#ifndef SOAP_TYPE_ArrayOfShipments
#define SOAP_TYPE_ArrayOfShipments (20)
#endif

/* struct ns1__DispatchReturnObject has binding name 'ns1__DispatchReturnObject' for type 'ns1:DispatchReturnObject' */
#ifndef SOAP_TYPE_ns1__DispatchReturnObject
#define SOAP_TYPE_ns1__DispatchReturnObject (19)
#endif

/* struct ns1__SenderData has binding name 'ns1__SenderData' for type 'ns1:SenderData' */
#ifndef SOAP_TYPE_ns1__SenderData
#define SOAP_TYPE_ns1__SenderData (18)
#endif

/* struct ns1__ShipmentPrice has binding name 'ns1__ShipmentPrice' for type 'ns1:ShipmentPrice' */
#ifndef SOAP_TYPE_ns1__ShipmentPrice
#define SOAP_TYPE_ns1__ShipmentPrice (17)
#endif

/* struct ns1__Sender has binding name 'ns1__Sender' for type 'ns1:Sender' */
#ifndef SOAP_TYPE_ns1__Sender
#define SOAP_TYPE_ns1__Sender (16)
#endif

/* struct ns1__ConfigProfile has binding name 'ns1__ConfigProfile' for type 'ns1:ConfigProfile' */
#ifndef SOAP_TYPE_ns1__ConfigProfile
#define SOAP_TYPE_ns1__ConfigProfile (15)
#endif

/* struct ns1__Shipment has binding name 'ns1__Shipment' for type 'ns1:Shipment' */
#ifndef SOAP_TYPE_ns1__Shipment
#define SOAP_TYPE_ns1__Shipment (12)
#endif

/* struct ns1__Option has binding name 'ns1__Option' for type 'ns1:Option' */
#ifndef SOAP_TYPE_ns1__Option
#define SOAP_TYPE_ns1__Option (11)
#endif

/* struct ns1__Recipient has binding name 'ns1__Recipient' for type 'ns1:Recipient' */
#ifndef SOAP_TYPE_ns1__Recipient
#define SOAP_TYPE_ns1__Recipient (9)
#endif

/* struct ns1__DocumentFile has binding name 'ns1__DocumentFile' for type 'ns1:DocumentFile' */
#ifndef SOAP_TYPE_ns1__DocumentFile
#define SOAP_TYPE_ns1__DocumentFile (8)
#endif

/* struct SOAP_ENV__Reason * has binding name 'PointerToSOAP_ENV__Reason' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (118)
#endif

/* struct SOAP_ENV__Detail * has binding name 'PointerToSOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (117)
#endif

/* struct SOAP_ENV__Code * has binding name 'PointerToSOAP_ENV__Code' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (111)
#endif

/* struct ns2__removeSenderResponse * has binding name 'PointerTons2__removeSenderResponse' for type 'ns2:removeSenderResponse' */
#ifndef SOAP_TYPE_PointerTons2__removeSenderResponse
#define SOAP_TYPE_PointerTons2__removeSenderResponse (106)
#endif

/* struct ns1__RemoveSenderReturnObject * has binding name 'PointerTons1__RemoveSenderReturnObject' for type 'ns1:RemoveSenderReturnObject' */
#ifndef SOAP_TYPE_PointerTons1__RemoveSenderReturnObject
#define SOAP_TYPE_PointerTons1__RemoveSenderReturnObject (105)
#endif

/* struct ns2__verifySenderResponse * has binding name 'PointerTons2__verifySenderResponse' for type 'ns2:verifySenderResponse' */
#ifndef SOAP_TYPE_PointerTons2__verifySenderResponse
#define SOAP_TYPE_PointerTons2__verifySenderResponse (101)
#endif

/* struct ns1__VerifySenderReturnObject * has binding name 'PointerTons1__VerifySenderReturnObject' for type 'ns1:VerifySenderReturnObject' */
#ifndef SOAP_TYPE_PointerTons1__VerifySenderReturnObject
#define SOAP_TYPE_PointerTons1__VerifySenderReturnObject (100)
#endif

/* struct ns2__addSenderResponse * has binding name 'PointerTons2__addSenderResponse' for type 'ns2:addSenderResponse' */
#ifndef SOAP_TYPE_PointerTons2__addSenderResponse
#define SOAP_TYPE_PointerTons2__addSenderResponse (96)
#endif

/* struct ns1__SenderData * has binding name 'PointerTons1__SenderData' for type 'ns1:SenderData' */
#ifndef SOAP_TYPE_PointerTons1__SenderData
#define SOAP_TYPE_PointerTons1__SenderData (95)
#endif

/* struct ns1__AddSenderReturnObject * has binding name 'PointerTons1__AddSenderReturnObject' for type 'ns1:AddSenderReturnObject' */
#ifndef SOAP_TYPE_PointerTons1__AddSenderReturnObject
#define SOAP_TYPE_PointerTons1__AddSenderReturnObject (94)
#endif

/* struct ns2__getPriceResponse * has binding name 'PointerTons2__getPriceResponse' for type 'ns2:getPriceResponse' */
#ifndef SOAP_TYPE_PointerTons2__getPriceResponse
#define SOAP_TYPE_PointerTons2__getPriceResponse (90)
#endif

/* struct ns1__PriceReturnObject * has binding name 'PointerTons1__PriceReturnObject' for type 'ns1:PriceReturnObject' */
#ifndef SOAP_TYPE_PointerTons1__PriceReturnObject
#define SOAP_TYPE_PointerTons1__PriceReturnObject (89)
#endif

/* struct ns2__getCertificateResponse * has binding name 'PointerTons2__getCertificateResponse' for type 'ns2:getCertificateResponse' */
#ifndef SOAP_TYPE_PointerTons2__getCertificateResponse
#define SOAP_TYPE_PointerTons2__getCertificateResponse (85)
#endif

/* struct ns1__CertificateReturnObject * has binding name 'PointerTons1__CertificateReturnObject' for type 'ns1:CertificateReturnObject' */
#ifndef SOAP_TYPE_PointerTons1__CertificateReturnObject
#define SOAP_TYPE_PointerTons1__CertificateReturnObject (84)
#endif

/* struct ns2__getSendersResponse * has binding name 'PointerTons2__getSendersResponse' for type 'ns2:getSendersResponse' */
#ifndef SOAP_TYPE_PointerTons2__getSendersResponse
#define SOAP_TYPE_PointerTons2__getSendersResponse (80)
#endif

/* struct ns1__SendersReturnObject * has binding name 'PointerTons1__SendersReturnObject' for type 'ns1:SendersReturnObject' */
#ifndef SOAP_TYPE_PointerTons1__SendersReturnObject
#define SOAP_TYPE_PointerTons1__SendersReturnObject (79)
#endif

/* struct ns2__getConfigProfilesResponse * has binding name 'PointerTons2__getConfigProfilesResponse' for type 'ns2:getConfigProfilesResponse' */
#ifndef SOAP_TYPE_PointerTons2__getConfigProfilesResponse
#define SOAP_TYPE_PointerTons2__getConfigProfilesResponse (75)
#endif

/* struct ns1__ConfigProfilesReturnObject * has binding name 'PointerTons1__ConfigProfilesReturnObject' for type 'ns1:ConfigProfilesReturnObject' */
#ifndef SOAP_TYPE_PointerTons1__ConfigProfilesReturnObject
#define SOAP_TYPE_PointerTons1__ConfigProfilesReturnObject (74)
#endif

/* struct ns2__getBalanceResponse * has binding name 'PointerTons2__getBalanceResponse' for type 'ns2:getBalanceResponse' */
#ifndef SOAP_TYPE_PointerTons2__getBalanceResponse
#define SOAP_TYPE_PointerTons2__getBalanceResponse (70)
#endif

/* struct ns1__BalanceReturnObject * has binding name 'PointerTons1__BalanceReturnObject' for type 'ns1:BalanceReturnObject' */
#ifndef SOAP_TYPE_PointerTons1__BalanceReturnObject
#define SOAP_TYPE_PointerTons1__BalanceReturnObject (69)
#endif

/* struct ns2__getDispatchStatusResponse * has binding name 'PointerTons2__getDispatchStatusResponse' for type 'ns2:getDispatchStatusResponse' */
#ifndef SOAP_TYPE_PointerTons2__getDispatchStatusResponse
#define SOAP_TYPE_PointerTons2__getDispatchStatusResponse (65)
#endif

/* struct ArrayOfDispatchIds * has binding name 'PointerToArrayOfDispatchIds' for type 'xsd:string' */
#ifndef SOAP_TYPE_PointerToArrayOfDispatchIds
#define SOAP_TYPE_PointerToArrayOfDispatchIds (64)
#endif

/* struct ns2__dispatchResponse * has binding name 'PointerTons2__dispatchResponse' for type 'ns2:dispatchResponse' */
#ifndef SOAP_TYPE_PointerTons2__dispatchResponse
#define SOAP_TYPE_PointerTons2__dispatchResponse (60)
#endif

/* struct ArrayOfOptions * has binding name 'PointerToArrayOfOptions' for type 'ns1:Option' */
#ifndef SOAP_TYPE_PointerToArrayOfOptions
#define SOAP_TYPE_PointerToArrayOfOptions (59)
#endif

/* struct ArrayOfRecipients * has binding name 'PointerToArrayOfRecipients' for type 'ns1:Recipient' */
#ifndef SOAP_TYPE_PointerToArrayOfRecipients
#define SOAP_TYPE_PointerToArrayOfRecipients (58)
#endif

/* struct ArrayOfDocumentFiles * has binding name 'PointerToArrayOfDocumentFiles' for type 'ns1:DocumentFile' */
#ifndef SOAP_TYPE_PointerToArrayOfDocumentFiles
#define SOAP_TYPE_PointerToArrayOfDocumentFiles (57)
#endif

/* struct ns1__DispatchReturnObject * has binding name 'PointerTons1__DispatchReturnObject' for type 'ns1:DispatchReturnObject' */
#ifndef SOAP_TYPE_PointerTons1__DispatchReturnObject
#define SOAP_TYPE_PointerTons1__DispatchReturnObject (56)
#endif

/* struct ns1__ShipmentPrice ** has binding name 'PointerToPointerTons1__ShipmentPrice' for type 'ns1:ShipmentPrice' */
#ifndef SOAP_TYPE_PointerToPointerTons1__ShipmentPrice
#define SOAP_TYPE_PointerToPointerTons1__ShipmentPrice (54)
#endif

/* struct ns1__ShipmentPrice * has binding name 'PointerTons1__ShipmentPrice' for type 'ns1:ShipmentPrice' */
#ifndef SOAP_TYPE_PointerTons1__ShipmentPrice
#define SOAP_TYPE_PointerTons1__ShipmentPrice (53)
#endif

/* struct ns1__Sender ** has binding name 'PointerToPointerTons1__Sender' for type 'ns1:Sender' */
#ifndef SOAP_TYPE_PointerToPointerTons1__Sender
#define SOAP_TYPE_PointerToPointerTons1__Sender (52)
#endif

/* struct ns1__Sender * has binding name 'PointerTons1__Sender' for type 'ns1:Sender' */
#ifndef SOAP_TYPE_PointerTons1__Sender
#define SOAP_TYPE_PointerTons1__Sender (51)
#endif

/* struct ns1__ConfigProfile ** has binding name 'PointerToPointerTons1__ConfigProfile' for type 'ns1:ConfigProfile' */
#ifndef SOAP_TYPE_PointerToPointerTons1__ConfigProfile
#define SOAP_TYPE_PointerToPointerTons1__ConfigProfile (50)
#endif

/* struct ns1__ConfigProfile * has binding name 'PointerTons1__ConfigProfile' for type 'ns1:ConfigProfile' */
#ifndef SOAP_TYPE_PointerTons1__ConfigProfile
#define SOAP_TYPE_PointerTons1__ConfigProfile (49)
#endif

/* char ** has binding name 'PointerTostring' for type 'xsd:string' */
#ifndef SOAP_TYPE_PointerTostring
#define SOAP_TYPE_PointerTostring (48)
#endif

/* struct ns1__Shipment ** has binding name 'PointerToPointerTons1__Shipment' for type 'ns1:Shipment' */
#ifndef SOAP_TYPE_PointerToPointerTons1__Shipment
#define SOAP_TYPE_PointerToPointerTons1__Shipment (46)
#endif

/* struct ns1__Shipment * has binding name 'PointerTons1__Shipment' for type 'ns1:Shipment' */
#ifndef SOAP_TYPE_PointerTons1__Shipment
#define SOAP_TYPE_PointerTons1__Shipment (45)
#endif

/* struct ns1__Option ** has binding name 'PointerToPointerTons1__Option' for type 'ns1:Option' */
#ifndef SOAP_TYPE_PointerToPointerTons1__Option
#define SOAP_TYPE_PointerToPointerTons1__Option (44)
#endif

/* struct ns1__Option * has binding name 'PointerTons1__Option' for type 'ns1:Option' */
#ifndef SOAP_TYPE_PointerTons1__Option
#define SOAP_TYPE_PointerTons1__Option (43)
#endif

/* struct ns1__Recipient ** has binding name 'PointerToPointerTons1__Recipient' for type 'ns1:Recipient' */
#ifndef SOAP_TYPE_PointerToPointerTons1__Recipient
#define SOAP_TYPE_PointerToPointerTons1__Recipient (41)
#endif

/* struct ns1__Recipient * has binding name 'PointerTons1__Recipient' for type 'ns1:Recipient' */
#ifndef SOAP_TYPE_PointerTons1__Recipient
#define SOAP_TYPE_PointerTons1__Recipient (40)
#endif

/* struct ns1__DocumentFile ** has binding name 'PointerToPointerTons1__DocumentFile' for type 'ns1:DocumentFile' */
#ifndef SOAP_TYPE_PointerToPointerTons1__DocumentFile
#define SOAP_TYPE_PointerToPointerTons1__DocumentFile (38)
#endif

/* struct ns1__DocumentFile * has binding name 'PointerTons1__DocumentFile' for type 'ns1:DocumentFile' */
#ifndef SOAP_TYPE_PointerTons1__DocumentFile
#define SOAP_TYPE_PointerTons1__DocumentFile (37)
#endif

/* struct ArrayOfShipmentsPrice * has binding name 'PointerToArrayOfShipmentsPrice' for type 'ns1:ShipmentPrice' */
#ifndef SOAP_TYPE_PointerToArrayOfShipmentsPrice
#define SOAP_TYPE_PointerToArrayOfShipmentsPrice (32)
#endif

/* struct ArrayOfSenders * has binding name 'PointerToArrayOfSenders' for type 'ns1:Sender' */
#ifndef SOAP_TYPE_PointerToArrayOfSenders
#define SOAP_TYPE_PointerToArrayOfSenders (28)
#endif

/* struct ArrayOfConfigProfiles * has binding name 'PointerToArrayOfConfigProfiles' for type 'ns1:ConfigProfile' */
#ifndef SOAP_TYPE_PointerToArrayOfConfigProfiles
#define SOAP_TYPE_PointerToArrayOfConfigProfiles (25)
#endif

/* struct ArrayOfShipments * has binding name 'PointerToArrayOfShipments' for type 'ns1:Shipment' */
#ifndef SOAP_TYPE_PointerToArrayOfShipments
#define SOAP_TYPE_PointerToArrayOfShipments (21)
#endif

/* float * has binding name 'PointerTofloat' for type 'xsd:float' */
#ifndef SOAP_TYPE_PointerTofloat
#define SOAP_TYPE_PointerTofloat (14)
#endif

/* int * has binding name 'PointerToint' for type 'xsd:int' */
#ifndef SOAP_TYPE_PointerToint
#define SOAP_TYPE_PointerToint (10)
#endif

/* _QName has binding name '_QName' for type 'xsd:QName' */
#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (6)
#endif

/* _XML has binding name '_XML' for type '' */
#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (5)
#endif

/* char * has binding name 'string' for type 'xsd:string' */
#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif

/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stub Functions                                            *
 *                                                                            *
\******************************************************************************/

    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__dispatch(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *login, char *api_USCOREpass, char *msg_USCOREtype, struct ArrayOfDocumentFiles *document_USCOREfiles, struct ArrayOfRecipients *recipients, struct ArrayOfOptions *options, struct ns2__dispatchResponse *_param_1);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__getDispatchStatus(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *login, char *api_USCOREpass, struct ArrayOfDispatchIds *dispatch_USCOREids, struct ns2__getDispatchStatusResponse *_param_1);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__getBalance(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *login, char *api_USCOREpass, struct ns2__getBalanceResponse *_param_1);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__getConfigProfiles(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *login, char *api_USCOREpass, char *msg_USCOREtype, struct ns2__getConfigProfilesResponse *_param_1);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__getSenders(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *login, char *api_USCOREpass, struct ns2__getSendersResponse *_param_1);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__getCertificate(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *login, char *api_USCOREpass, char *dispatch_USCOREid, int certificate_USCOREtype, struct ns2__getCertificateResponse *_param_1);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__getPrice(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *login, char *api_USCOREpass, char *msg_USCOREtype, struct ArrayOfDocumentFiles *document_USCOREfiles, struct ArrayOfRecipients *recipients, int config_USCOREid, struct ns2__getPriceResponse *_param_1);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__addSender(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *login, char *api_USCOREpass, struct ns1__SenderData *sender_USCOREdata, enum xsd__boolean accept_USCOREterms, struct ns2__addSenderResponse *_param_1);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__verifySender(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *login, char *api_USCOREpass, int sender_USCOREid, char *verification_USCOREcode, struct ns2__verifySenderResponse *_param_1);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__removeSender(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *login, char *api_USCOREpass, int sender_USCOREid, struct ns2__removeSenderResponse *_param_1);

/******************************************************************************\
 *                                                                            *
 * Server-Side Operations                                                     *
 *                                                                            *
\******************************************************************************/

    /** Web service operation 'ns2__dispatch' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 ns2__dispatch(struct soap*, char *login, char *api_USCOREpass, char *msg_USCOREtype, struct ArrayOfDocumentFiles *document_USCOREfiles, struct ArrayOfRecipients *recipients, struct ArrayOfOptions *options, struct ns2__dispatchResponse *_param_1);
    /** Web service operation 'ns2__getDispatchStatus' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 ns2__getDispatchStatus(struct soap*, char *login, char *api_USCOREpass, struct ArrayOfDispatchIds *dispatch_USCOREids, struct ns2__getDispatchStatusResponse *_param_1);
    /** Web service operation 'ns2__getBalance' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 ns2__getBalance(struct soap*, char *login, char *api_USCOREpass, struct ns2__getBalanceResponse *_param_1);
    /** Web service operation 'ns2__getConfigProfiles' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 ns2__getConfigProfiles(struct soap*, char *login, char *api_USCOREpass, char *msg_USCOREtype, struct ns2__getConfigProfilesResponse *_param_1);
    /** Web service operation 'ns2__getSenders' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 ns2__getSenders(struct soap*, char *login, char *api_USCOREpass, struct ns2__getSendersResponse *_param_1);
    /** Web service operation 'ns2__getCertificate' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 ns2__getCertificate(struct soap*, char *login, char *api_USCOREpass, char *dispatch_USCOREid, int certificate_USCOREtype, struct ns2__getCertificateResponse *_param_1);
    /** Web service operation 'ns2__getPrice' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 ns2__getPrice(struct soap*, char *login, char *api_USCOREpass, char *msg_USCOREtype, struct ArrayOfDocumentFiles *document_USCOREfiles, struct ArrayOfRecipients *recipients, int config_USCOREid, struct ns2__getPriceResponse *_param_1);
    /** Web service operation 'ns2__addSender' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 ns2__addSender(struct soap*, char *login, char *api_USCOREpass, struct ns1__SenderData *sender_USCOREdata, enum xsd__boolean accept_USCOREterms, struct ns2__addSenderResponse *_param_1);
    /** Web service operation 'ns2__verifySender' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 ns2__verifySender(struct soap*, char *login, char *api_USCOREpass, int sender_USCOREid, char *verification_USCOREcode, struct ns2__verifySenderResponse *_param_1);
    /** Web service operation 'ns2__removeSender' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 ns2__removeSender(struct soap*, char *login, char *api_USCOREpass, int sender_USCOREid, struct ns2__removeSenderResponse *_param_1);

/******************************************************************************\
 *                                                                            *
 * Server-Side Skeletons to Invoke Service Operations                         *
 *                                                                            *
\******************************************************************************/

SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__dispatch(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__getDispatchStatus(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__getBalance(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__getConfigProfiles(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__getSenders(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__getCertificate(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__getPrice(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__addSender(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__verifySender(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__removeSender(struct soap*);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapStub.h */
